### ISSUE TITLE
Names are too long! 

### ISSUE THREAD

**Issue by ProLoser** [joshdmiller/angular-placeholders#1]
Seriously, I use placeholders to be quick, short, and painless. The directive (and namespace) is
# HUGE

Any thought as to just using a `ph-` prefix? Otherwise fairly awesome :+1:

Suggested directive contractions:
- ph-img="24x24"
- ph-text="{{numSentences}}x{{numPara}}"

No reason to have multiple attributes :smile:

**Comment by ProLoser** [comment]
Or even call it 'lipsum' if you want to be explicit.

**Comment by joshdmiller** [comment]
@ProLoser Yes, as I began using it I started thinking the same thing. I have a couple more changes to push in the next few days, and I'll _definitely_ shorten the namespace.

For the contraction, I've been trying to think of a good way to do it; one of the features I was going to add was to allow customization of the number sentences per paragraph (which the service supports, but not the directive), so I had two separate attributes. But I **love** your recommendation - so much simpler! To allow for a few more options, I'm thinking something like:
- `5x5`: 5 sentences x 5 paragraphs
- `5x`: 5 sentences with no paragraphs (numSentences now) 
- `5` or `x5`: 5 paragraphs with a random # of sentences (numParagraphs now)

What do you think?

**Comment by ProLoser** [comment]
Why don't you just use time-syntax?

phTxt="5s2p" or something. Good point that "2" should probably just be paragraphs. Or leave it as is? fuck iunno.

OR actually keep the old syntax but do 5x5 for 5 sentences x 5para, 5 = 5 para, and just make people do 5x1 (god forbid) rather than have 5x or x5 options. No one really needs that

Lol now I'm worried 'ph' is going to confuse people vs 'lipsum', but at least it's better!

**Comment by joshdmiller** [comment]
The time-like syntax would probably be the least confusing as there's no need to remember ordering, etc, but I'll put more thought into this.

As for `ph` confusing people, I'm not really worried about it. These are mostly design and development directives, so the risk of namespace clashing is lessened and I don't see a common use case being in a super-massive codebase where keeping mental track of what `ph` means would be problematic. Considering that these are intended to save time, losing a little bit of clarity is a small tradeoff I'm willing to make. But we'll see how the community reacts. :-)

**Comment by joshdmiller** [comment]
Closing this as the main issue has been merged with #3. I've moved the secondary issue to #4 for clarity.
