### ISSUE TITLE
bower registration

### ISSUE THREAD

**Issue by yahyaKacem** [joshdmiller/angular-placeholders#11]
hi, I'm registering this in the bower registry, so it will be available for install like this:

``` command-line
bower install angular-placeholders 
```

Thanks.

**Comment by joshdmiller** [comment]
@yahaKacem - Thanks for contributing! That was on my unofficial "to do" list.

I'm not super-familiar with Bower, but the link on the Bower registry is broken - I think the URL is missing the "http://". How can we get that fixed?

Though I think the answer is "no", is it possible to force Bower into using a particular branch? The master branch has active development in advance of the gh-pages site and contains breaking changes. In a few days, I will set up a release branch as the default. What's the best way to handle this (common) use case with Bower?

**Comment by yahyaKacem** [comment]
actually I already registered it with this branch like this:

```
bower register angular-placeholders https://github.com/joshdmiller/angular-placeholders.git
```

so now when i run this:

```
bower search angular-placeholders 
```

it will print out this:

> Search results:
> 
>  - angular-placeholders git://github.com/joshdmiller/angular-placeholders.git

before i used to install it like this:

```
bower install https://github.com/joshdmiller/angular-placeholders.git
```

now like this:

```
bower install angular-placeholders 
```

**Comment by joshdmiller** [comment]
I meant that by default Bower is using the "master" branch of the repository. Is it possible to make it use a different branch?

**Comment by yahyaKacem** [comment]
I'm not sure, I think if you provide a version or a commit's hash like this:

```
bower install angular-placeholder#<<hash or version here>>
```

I think that will work but about branches i have no idea.

**Comment by Iristyle** [comment]
FYI - 

When I pulled down what was registered in Bower already, it wasn't usable.

I've temporarily created this until you decide what you want to do
https://github.com/Iristyle/bower-angular-placeholders

Unfortunately Bower isn't really great when there is a build process associated with the assets.  It's not like NPM, where it kicks off node-gyp to build anything you might need locally.

So if you want to continue to use this repo inside of Bower, you're going to need to create a build, stuff it back into the source tree, point to it from a `component.json`, and tag it with git tags.

HTH

**Comment by geyang** [comment]
I just ran into this problem too. I think a good quick fix at this moment is just to include pre-builds in the github repository in the /dist folder.

**Comment by Soviut** [comment]
This is still pretty messy. There are no ignores so all the demos and unrelated files are included. Also, the version specified when the `--save-dev` option is used comes out at `"*"`.

**Comment by diosney** [comment]
For this to work fine, I think is it needed a precompilation of the files, include them in the repo files and then bump the version, or at least this is a way that other libraries use.
