### ISSUE TITLE
Error when img tags are generated dynamically?

### ISSUE THREAD

**Issue by yahyaKacem** [joshdmiller/angular-placeholders#12]
Hi again, see [plnkr](http://embed.plnkr.co/we0YGl9VQ2gCai3try8p/preview) for more details.
you need to inspect with chrome developer tools to see error it appears as many time as the number of images:

> TypeError: Cannot call method 'match' of undefined
>     at Object.fn (http://run.plnkr.co/plunks/we0YGl9VQ2gCai3try8p/angular-placeholders.img.js:54:40)
>     at Object.e.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js:84:307)
>     at Object.e.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js:86:376)
>     at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js:92:400)
>     at n (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js:95:472)
>     at XMLHttpRequest.q.onreadystatechange (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js:96:380) angular.min.js:60
> (anonymous function)

image showing the error:
![Untitled](https://f.cloud.github.com/assets/844900/129365/25f13c8c-6fdb-11e2-8c24-90f8d7e2c1d2.png)

Thanks in advance.

**Comment by joshdmiller** [comment]
This is a bug, but is safe to ignore in the short term. The `$watch` is called with an undefined value before the real one, causing it to error out. This is expected, but not checked. The error can be removed by checking for the undefined value:

``` js
scope.$watch( 'dimensions', function ( dimensions ) {
  if ( ! angular.isDefined( dimensions ) ) return;
  // etc...
});
```

Feel free to submit a pull request. :-)
